// <auto-generated />
using System;
using AppsTester.Controller;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AppsTester.Controller.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211127200629_RemoveUselessProperties")]
    partial class RemoveUselessProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AppsTester.Controller.Submissions.SubmissionCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendingDateTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmissionCheckStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubmissionChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
