name: Update Controller

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: android-testing-system
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file AppsTester.Controller/Dockerfile --tag appstester-controller:${{ github.sha }}
  restart:
    runs-on: android-testing-system
    needs: build
    steps:
    - name: stop running image
      run: sudo docker stop appstester-controller
    - name: remove running image
      run: sudo docker rm appstester-controller
    - name: start built image
      run: sudo docker run -d appstester-controller:${{ github.sha }} --name appstester-controller
