name: Build Controller Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: android-testing-system
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file AppsTester.Controller/Dockerfile --tag appstester-controller:$(date +%s)
