name: MIREA Update Android Checker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: mirea-testing-system
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file AppsTester.Checker.Android/Dockerfile --tag appstester-android-checker:${{ github.sha }}
  restart:
    runs-on: mirea-testing-system
    needs: build
    environment: mirea
    steps:
    - name: stop running image
      run: sudo docker stop appstester-android-checker-mirea || true
    - name: remove running image
      run: sudo docker rm appstester-android-checker-mirea || true
    - name: start built image
      run: >
        sudo docker run
        -d
        --name appstester-android-checker-mirea
        --restart=unless-stopped
        --net=host -e 'ConnectionStrings__DefaultConnection=${{ secrets.DATABASE_CONNECTION_STRING }}'
        -e 'ConnectionStrings__RabbitMq=${{ secrets.RABBITMQ_CONNECTION_STRING }}'
        -e 'Adb__Host=${{ secrets.ADB_HOST }}'
        -e 'Controller__Url=${{ secrets.CONTROLLER_URL }}'
        -e 'OtlpExporterEndpoint=${{ secrets.OTLP_EXPORTER_ENDPOINT }}'
        -e 'Sentry__Dsn=${{ secrets.SENTRY_DSN }}'
        appstester-android-checker:${{ github.sha }}
